### ISSUE TITLE
Allow simplified byte values for options (kB, MB, GB, TB)

### ISSUE THREAD

**Issue by keithf4** [keithf4/pg_bloat_check#13]
See subject

**Comment by keithf4** [comment]
@richyen I've merged this in and committed up version 2.7.0. If you wouldn't mind giving it one look over, I'll tag the new release then.

**Comment by richyen** [comment]
Thanks!  I think it looks good 👍🏻

**Comment by keithf4** [comment]
Tagged. Thanks for the contribution!
