### ISSUE TITLE
Toast table is not being checked, hence bloat amount is vastly wrong

### ISSUE THREAD

**Issue by jpuris** [keithf4/pg_bloat_check#15]
I've got fairly large table that is pushing large hstore to toast, however `pg_bloat_check.py` reports the size of the table to be much less. I suspect it is not accounting for any toast.

For example
```bash
/usr/bin/pg_bloat_check.py -c "dbname=db user=postgres" --recovery_mode_norun --bloat_schema=monitor --min_size=107374182
1. public.asset (t) ..........................................................(41.72%) 2588 MB wasted
[..]
```

```psql
select
    table_name,
    pg_size_pretty(pg_relation_size(table_name, 'main')) as main,
    pg_size_pretty(pg_relation_size(table_name, 'fsm'))  as fsm,
    pg_size_pretty(pg_relation_size(table_name, 'vm'))   as vm,
    pg_size_pretty(pg_relation_size(table_name, 'init')) as init,
    pg_size_pretty(pg_table_size(table_name))            as table,
    pg_size_pretty(pg_indexes_size(table_name))          as indexes,
    pg_size_pretty(pg_total_relation_size(table_name))   as total
from
    information_schema.tables
where
    table_schema = 'public' and table_name = 'asset'
;
```

```json
[
  {
    "table_name": "asset",
    "main": "6203 MB",
    "fsm": "1584 kB",
    "vm": "104 kB",
    "init": "0 bytes",
    "table": "149 GB",
    "indexes": "17 GB",
    "total": "166 GB"
  }
]
```

It would seem the 42% (2588 MB) would be coming from `"main": "6203 MB"` which is no where close to total - indexes.

**Comment by keithf4** [comment]
I don't use the `pg_relation_size()` function directly, I just use the `table_len` column from the `pgstattuple` extension for reporting the size.

https://www.postgresql.org/docs/current/pgstattuple.html

But yeah, looks like toast isn't getting included directly with the relation itself when you run pgstattuple against it. However, if the toast table itself is bloated, it should show up as its own entry separately in the bloat report. I don't filter them out when I get the list of tables to check for bloat, so they should be there if they meet your bloat filter requirements.

Could you please find out which toast table is associated with your `asset` table and see if it's in the report and what it's reporting its bloat to be? If you're not sure what toast table is associated with a table, you can find that in the `pg_class` system catalog. For example:
```
select oid, relname, reltoastrelid, reltoastrelid::regclass from pg_class where relname = 'asset';;
  oid   | relname | reltoastrelid |      reltoastrelid       
--------+---------+---------------+--------------------------
 426250 | asset   |        426253 | pg_toast.pg_toast_426250
```

I'll have to investigate whether trying to merge the table and its underlying toast together for the report will distort the result. Like I'm wondering if the base table's bloat at 41% like your seeing wouldn't get reported if its underlying toast table was say only 2% bloated (since it's so much larger). Wondering if that's even possible.

Either way, fixing the base table or its toast table will require running the cleanup in a manner that would affect both anyway. So just need to figure out the clearest way to report this.

**Comment by jpuris** [comment]
Hey! Thanks for the quick reply, please see my findings below

**_Associated toast table and estimated size_**
```sql
select
    pcp.relname                                                           as primary_name,
    pcp.relpages                                                          as primary_page_count,
    pcp.relpages * current_setting('block_size')::numeric                 as primary_size,
    pg_size_pretty(pcp.relpages * current_setting('block_size')::numeric) as primary_size_pretty,
    pct.relname                                                           as toast_name,
    pct.relpages                                                          as toast_page_count,
    pct.relpages * current_setting('block_size')::numeric                 as toast_size,
    pg_size_pretty(pct.relpages * current_setting('block_size')::numeric) as toast_size_pretty
from
    pg_class      pcp
    join pg_class pct on pct.oid = pcp.reltoastrelid
where
    pcp.relname = 'asset'
;
```
```json
[
  {
    "primary_name": "asset",
    "primary_page_count": 794026,
    "primary_size": 6504660992,
    "primary_size_pretty": "6203 MB",
    "toast_name": "pg_toast_24265924",
    "toast_page_count": 18454675,
    "toast_size": 151180697600,
    "toast_size_pretty": "141 GB"
  }
]
```

**_pgstatstuple report_**
```sql
select
    'asset' as table_name,
    *
from
    pgstattuple('asset')
;
```
```json
[
  {
    "table_name": "asset",
    "table_len": 6504660992,
    "tuple_count": 6626744,
    "tuple_len": 2984519981,
    "tuple_percent": 45.88,
    "dead_tuple_count": 95512,
    "dead_tuple_len": 39263538,
    "dead_tuple_percent": 0.6,
    "free_space": 3235926980,
    "free_percent": 49.75
  }
]
```

Calling pgstattuple on primary table, does not include toast :(

**Comment by jpuris** [comment]
Not sure if relevant, but the PG version this is run on is 9.4.24
`PostgreSQL 9.4.24 on x86_64-pc-linux-gnu (Ubuntu 9.4.24-1.pgdg18.04+1), compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit`

**Comment by keithf4** [comment]
So is the toatst table being included in the report, or can you run pgstattuple directly against the toast table?

**Comment by jpuris** [comment]
It is not in the report, as a seperate entry.
None of the toast tables (we have couple other in use) are in the report for that matter.

When pgstattuple is run directly against the toast table, I get an error
```sql> select
         'company' as table_name,
         *
     from
         pgstattuple('pg_toast_24265924')
[2019-09-04 15:26:19] [42P01] ERROR: relation "pg_toast_24265924" does not exist
```

**Comment by keithf4** [comment]
You may have to schema qualify the toast table. They're all located in the `pg_toast` schema.

**Comment by jpuris** [comment]
You're right! The toast tables are not in public.
```sql
select
    'pg_toast.pg_toast_24265924' as table_name,
    *
from
    pgstattuple('pg_toast.pg_toast_24265924')
;
```
```json
[
  {
    "table_name": "asset",
    "table_len": 151180697600,
    "tuple_count": 15602766,
    "tuple_len": 22802650288,
    "tuple_percent": 15.08,
    "dead_tuple_count": 57053,
    "dead_tuple_len": 81864316,
    "dead_tuple_percent": 0.05,
    "free_space": 127374200700,
    "free_percent": 84.25
  }
]```

As you can see, it has crazy amount of accumulated bloat, which is what I suspected. However there is no record of it in the report, when I run `pg_bloat_check.py`.

This table is the largest one our of all and alone took 14m to run `pgstattuple()` on it. However when I run `pg_bloat_check.py` it takes less than a minute, which makes me think, the script is not running pgstattuple on toasts at all.

**Comment by keithf4** [comment]
So yeah, looks like I wasn't getting toast tables when I was scanning. Was only checking for `pg_class.relkind` equal to `m` or `r` but not `t`. Will see about getting that fixed. 

Will still have to report the toast table bloat separately from the main table since, as you can see, their bloat status can vary widely and trying to combine them would be rather inaccurate.  Will still require fixing via the main table, however, since your not really supposed to interact with toast tables directly.

**Comment by keithf4** [comment]
Below is the simple fix that should include toast tables in the result. Mind applying this patch and see how it works?

Also going to see if I can maybe make the output a little more user friendly to identify which table the toast belongs to then.
```
diff --git a/pg_bloat_check.py b/pg_bloat_check.py
index d805002..2f865d8 100755
--- a/pg_bloat_check.py
+++ b/pg_bloat_check.py
@@ -172,7 +172,7 @@ def get_bloat(conn, exclude_schema_list, include_schema_list, exclude_object_lis
     sql_tables = """ SELECT c.oid, c.relkind, c.relname, n.nspname, 'false' as indisprimary, c.reloptions
                     FROM pg_catalog.pg_class c
                     JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
-                    WHERE relkind IN ('r', 'm')
+                    WHERE relkind IN ('r', 'm', 't')
                     AND c.relpersistence <> 't' """
 
     sql_indexes = """ SELECT c.oid, c.relkind, c.relname, n.nspname, i.indisprimary, c.reloptions 
```

**Comment by jpuris** [comment]
Patched, but no change :(
```bash
time sudo -u postgres /usr/bin/pg_bloat_check.py -c "dbname=db user=postgres" --recovery_mode_norun --bloat_schema=monitor
```
run in 4m, with not a single toast table.

It starts with 3.2 GB bloat for primary table.
```
1. public.asset (t) ...........................................................(52.8%) 3275 MB wasted
[..]
```
I can see the select itself, after the change returns the toast tables.

**Comment by jpuris** [comment]
#16 adds ` --include-toast`, which when used disables the hardocoded exclude for `pg_toast` schema.

**Comment by keithf4** [comment]
Ok, so wasn't as simple a fix as I first thought at first. Thanks for catching most of the other spots in your PR. Big part is that I was actually specifically filtering out the `pg_toast` schema. So commented that out for now. Here's a branch with all the changes so far to just get things working

https://github.com/keithf4/pg_bloat_check/tree/toast

I'm seeing some toast tables show up in the report myself now, so could you please run this yourself and let me know how it goes? 

Still trying to work out a clearer way to report which table it goes along with.

**Comment by keithf4** [comment]
Updated that branch to include the associated real table along with the toast table in the simple output. Please let me know if that's working ok for you.

**Comment by jpuris** [comment]
Its working!

```bash
time ./pg_bloat_check.py -c "dbname=db user=postgres" --recovery_mode_norun --bloat_schema=monitor --mode=tables
1. pg_toast.pg_toast_24265924 (t) .............................................(88.42%) 124 GB wasted
      Real table: public.asset
2. public.asset (t) ..........................................................(62.17%) 3857 MB wasted
[..]
```
```sql
select * from monitor.bloat_stats order by free_space_bytes desc limit 2;
```
```json
[
  {
    "oid": 24265935,
    "schemaname": "pg_toast",
    "objectname": "pg_toast_24265924",
    "objecttype": "toast_table",
    "size_bytes": 151180697600,
    "live_tuple_count": 11366206,
    "live_tuple_percent": 10.97,
    "dead_tuple_count": 142349,
    "dead_tuple_size_bytes": 207954431,
    "dead_tuple_percent": 0.14,
    "free_space_bytes": 133467592556,
    "free_percent": 88.28,
    "stats_timestamp": "2019-09-05 08:52:18.081272",
    "approximate": false,
    "relpages": 18454675,
    "fillfactor": 100
  },
  {
    "oid": 24265924,
    "schemaname": "public",
    "objectname": "asset",
    "objecttype": "table",
    "size_bytes": 6504660992,
    "live_tuple_count": 4667007,
    "live_tuple_percent": 34.06,
    "dead_tuple_count": 169801,
    "dead_tuple_size_bytes": 65272648,
    "dead_tuple_percent": 1,
    "free_space_bytes": 3978753584,
    "free_percent": 61.17,
    "stats_timestamp": "2019-09-05 09:05:34.128654",
    "approximate": false,
    "relpages": 794026,
    "fillfactor": 100
  }
]
```

Potential improvements:
1. Percentage does not match between cli output and whats stored in `bloat_stats`. It is slightly off. Not a big deal, but still.
2. Not sure if necessary, but I think it would be helpful, if there would be additional attribute for main table.. This way I can group by something like `coalesce(mainobjectname, objectname)` to get the sum of the bloat on individual table. This can be of course worked around by finding it out via PG functions etc..
3. When schemaname is specified in cli, will it include toast ?

**Comment by keithf4** [comment]
> Its working!

Awesome! Thank you!

> Potential improvements:
> 
> 1. Percentage does not match between cli output and whats stored in `bloat_stats`. It is slightly off. Not a big deal, but still.

The CLI "simple" percentage output in a combination of the `dead_tuple_percent` and `free_percent` and then also then accounting for `fill_factor`. The raw output has that all split up for more thorough investigation if needed, but the true bloat amount is a calculation using those values.

> 2. Not sure if necessary, but I think it would be helpful, if there would be additional attribute for main table.. This way I can group by something like `coalesce(mainobjectname, objectname)` to get the sum of the bloat on individual table. This can be of course worked around by finding it out via PG functions etc..

That's the thing, though, any sort of combination of these values isn't really a true representation of the bloat status. The main table and TOAST table are independently bloated and if one greatly differs from the other, combining them could be confusing. It's better to see the status of each individually so you can see how bad one or the other is. It's just that if either one is bloated, you have to fix it through the main table.

I thought about adding the real table to the bloat table, but the toast table name can actually be changed out from under the real table name during certain table rewrite operations (vacuum full). So I figured it was better to look that up in real-time at the time the report is output. You can always see which main table a toast table is associated with by looking at the `pg_class.reltoastrelid` column. I do store the OID of the toast table in the bloat monitoring table, so you can join it against that.

> 3. When schemaname is specified in cli, will it include toast ?

It shows the `pg_toast` schema in the cli output. Or do you mean something else?

**Comment by jpuris** [comment]
Feedback on points `#1` and `#2` does sound fair. I will ask postgres, which is the table the toast belongs to when asking for bloat data.

`#3` It is about `--schema` cli opt.
I've actually confirmed that when `--schema=public` is used, toast table bloat is not reported using the `toast` branch updates.

Current workaround is to not include `-schema`, and then adjust the query done against `bloat_stats` table. It has however, the undesired overhead of scanning the system schemas etc, however this is something I can live with.

**Comment by keithf4** [comment]
Ahh yeah. Should probably include relevant toast tables when `--schema` is used. Just have to figure out a way to only scan the toast tables for the relevant schema. Will see what I can figure out. Good catch!

**Comment by keithf4** [comment]
Apologies for the delay. I believe I got the schema/table filtering working for toast table results as well. Would you mind giving the `toast` branch a try again?

https://github.com/keithf4/pg_bloat_check/tree/toast

**Comment by jpuris** [comment]
Looks good!

Following
```
/usr/bin/pg_bloat_check.py -c "dbname=db user=postgres" --recovery_mode_norun --bloat_schema=monitor --min_size=107374182 --schema=public
```
Produces the desired results.

Thank you so much, @keithf4.

**Comment by keithf4** [comment]
Great!

As a recommendation, I wouldn't skip the pg_catalog schema. And actually, I may include it by default unless it's specifically excluded with the -N option. Depending on the database usage, the catalogs can get bloated and can lead to more serious query performance issues.

**Comment by keithf4** [comment]
Fixed schema include to always include pg_catalog. Shouldn't affect runtime since most times these tables are very small. And if you're setting a minimum size, they'll likely be skipped anyway unless they're really bloated. 

Made a new issue to see about allow schema include & exclude options to be used together. Currently they're mutually exclusive and fixing it was more work than I want to do right now before getting this issue's fix out.

Will push out new version tomorrow then unless anything else comes up.

**Comment by keithf4** [comment]
Version 2.6.1 is released. Thanks for reporting the issue and your help testing!

**Comment by jpuris** [comment]
Thank you, @keithf4. Awesome work!
