### ISSUE TITLE
Running into error

### ISSUE THREAD

**Issue by DHorneDBA** [keithf4/pg_bloat_check#19]
I get this error when running the script....not sure why it is not skipping materalized views, but it is preventing report generation although the tables appear to be populated.....

Unexpected object type encountered in stats table. Please report this bug to author with value found: materialized_view

**Comment by keithf4** [comment]
That actually appears to be a bug! Will see about fixing that ASAP. Thanks for reporting it!

**Comment by keithf4** [comment]
Can you see if this diff fixes things for you?
```
diff --git a/pg_bloat_check.py b/pg_bloat_check.py
index 7df45a7..b1d9cf2 100755
--- a/pg_bloat_check.py
+++ b/pg_bloat_check.py
@@ -696,6 +696,8 @@ if __name__ == "__main__":
                     type_label = 'i'
                 elif r['objecttype'] == 'index_pk':
                     type_label = 'p'
+                elif r['objecttype'] == 'materialized_view':
+                    type_label = 'mv'
                 else:
                     print("Unexpected object type encountered in stats table. Please report this bug to author with value found: " + str(r['objecttype']))
                     sys.exit(2)
```

**Comment by DHorneDBA** [comment]
Wow that was quick....it makes sense that it would based on the code, unfortunately I am beyond newbie with github and python and so when I add the code I keep getting:


  File "./pg_bloat_check.py", line 699
    elif r['objecttype'] == 'materialized_view':
    ^
IndentationError: unexpected indent

I am not expecting you to help me with this, but i think your code has fixed things....

**Comment by DHorneDBA** [comment]
Nevermind fixed it and yes it fixes things...thanks Keith

**Comment by keithf4** [comment]
New version has been pushed up. Thanks again!
