### ISSUE TITLE
Not getting output 

### ISSUE THREAD

**Issue by bhatiaravi18** [keithf4/pg_bloat_check#23]
When I run the blot check script it does not returns any output , anything is being missed here :

[postgres@myhost pg_bloat_check-master]$ PGPASSWORD=**** pg_bloat_check.py -c "host=10.202.10.40 dbname=META_5.1 user=postgres" -z 10485760 -p 10 -s 5242880 --create_stats_table --bloat_schema=monitoring
[postgres@myhost pg_bloat_check-master]]$

**Comment by keithf4** [comment]
You just ran the `--create_stats_table` option. That just creates the tables that the results will be inserted into. Run again without that option to actually run the scan.

**Comment by bhatiaravi18** [comment]
Hi Keith,

I tried without create table as well it jeeps on running without any output 

Regards:
Ravi

**Comment by keithf4** [comment]
If it's still running and hasn't returned anything, it's likely scanning tables and storing resutls. You can log into your database and check the bloat tables that were created (`bloat_stats`, `bloat_tables` and/or `bloat_indexes`) to see if they have any contents. Or check pg_stat_activity to see which tables it's working on.

As the README notes, using pgstattuple to check for bloat like this script does can take a while, especially on a large database. If you're just learning how to use this, I'd suggest targeting a single table with the -t option to have it run a bit quicker.

**Comment by keithf4** [comment]
Closing this issue. Please feel free to re-open if you are still having any issues.
