### ISSUE TITLE
Conversion to python3

### ISSUE THREAD

**Issue by victor-sudakov** [keithf4/pg_bloat_check#26]
Python2 is being removed from distributions, is it safe to run the script under python3? I tried running it under python3 on a test database and the result looked OK but what would more knowledgeable people say?

**Comment by keithf4** [comment]
This should be Python3 compatible. If you're having any issues with it, please let me know.

**Comment by victor-sudakov** [comment]
> This should be Python3 compatible.

Great! Can you please mention this in the Readme somewhere?

> If you're having any issues with it, please let me know.

OK.

**Comment by keithf4** [comment]
README has been updated to mention it is python3 compatible

**Comment by victor-sudakov** [comment]
> README has been updated to mention it is python3 compatible

Thank you!
