### ISSUE TITLE
Fails on pgsql 9.2

### ISSUE THREAD

**Issue by Sxooter** [keithf4/pg_bloat_check#5]
Getting this error on 9.2:

`psycopg2.ProgrammingError: column "indislive" does not exist
LINE 13:                     AND indislive = 'true' 
`

**Comment by Sxooter** [comment]
So I chopped that one line out and it seems to be working ( as in it doesn't fail)

**Comment by keithf4** [comment]
Thanks for checking! Probably be good to have a version check in place anyway for better long term support. Will fix this as soon as I have some time.

**Comment by keithf4** [comment]
This has been fixed in version 2.1.1

**Comment by Sxooter** [comment]
Thanks!
