### ISSUE TITLE
script cannot dedect beta2

### ISSUE THREAD

**Issue by devrimgunduz** [keithf4/pg_bloat_check#9]
Hi,

Probably a minor issue, but I'll still report:

$  /usr/bin/pg_bloat_check.py  -c "host=localhost port=5496"
Traceback (most recent call last):
  File "/usr/bin/pg_bloat_check.py", line 501, in <module>
    get_bloat(conn, tuple(exclude_schema_list), tuple(include_schema_list), exclude_object_list)
  File "/usr/bin/pg_bloat_check.py", line 171, in get_bloat
    if int(pg_version[0]) >= 9 and int(pg_version[1]) >= 3:
ValueError: invalid literal for int() with base 10: '6beta2'

Regards, Devrim

**Comment by devrimgunduz** [comment]
FWIW, this does not happen while using --create_stats_table.

**Comment by keithf4** [comment]
Yeah, I ran into this myself. I'll see if I can handle it in the next version. It's because it only does a version check at a later point in the script.

**Comment by keithf4** [comment]
I've got this fixed in the next version I'm working on. Can test it out in this branch:

https://github.com/keithf4/pg_bloat_check/tree/rebuild

**Comment by keithf4** [comment]
This was fixed in v2.3.0. Let me know if there's any issues.
